decimal = int(input("Enter an Decimal: "))
print("="*20)
print("NUMBER SYSTEM CONVERTER")
print("="*20)
print(f"Decimal : {decimal}")
print(f"Binary: {bin(decimal)}")
print(f"Octal: {oct(decimal)}")
print(f"Hexadecimal: {hex(decimal)}")
print("="*20)