s_name = input("Enter store name: ")
c_name = input("Enter customer name: ")
p_name = input("Enter product name: ")
quantity = int(input("Enter quantity: "))
price = float(input("Enter Price: "))
gst = int(input("Enter GST percentage: "))
tax = (gst/100)*(quantity*price)
total = price*quantity
print("="*50)
print(f"{s_name:^50}")
print("="*50, "\n")
print(f"Customer:{c_name:>7} \n")
print("-"*50)
print(f"Items                  Qty    Price     Total")
print("-"*50)
print(f"{p_name:<23}{quantity:<7}${price:<10.2f}${total:<5.2f}")
print("-"*50,"\n")
print(f"Subtotal${total:>30.2f}")
print(f"GST({gst}%)${tax:>30.2f}")
print("-"*50)
print(f"Grand Total${tax+total:>27.2f}\n")
print("="*50)
print("            Thank you! Visit again :)")
print("="*50)